// <auto-generated />
using System;
using Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513054402_mgr3")]
    partial class mgr3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Domain.TaxParameters.DisabilityDegree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Degree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DisabilityDegrees");
                });

            modelBuilder.Entity("Domain.TaxParameters.EconomicIndicators", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InflationRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumWageIncreaseRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RevaluationRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EconomicIndicators");
                });

            modelBuilder.Entity("Domain.TaxParameters.IncomeTaxBracket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bracket")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IncomeTaxBrackets");
                });

            modelBuilder.Entity("Domain.TaxParameters.MinimumWage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ceiling")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetiredNetSalary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MinimumWages");
                });

            modelBuilder.Entity("Domain.TaxParameters.SSParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActiveEmployeeSSRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActiveEmployeeUIRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActiveEmployerSSRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActiveEmployerUIRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetiredEmployeeSSRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetiredEmployerSSRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SSParams");
                });

            modelBuilder.Entity("Domain.TaxParameters.StampTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StampTaxes");
                });
#pragma warning restore 612, 618
        }
    }
}
